# Generated by Django 5.2.8 on 2026-01-08 06:52

import django.db.models.deletion
import iam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise_core', '0001_initial'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='folder',
            field=models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder'),
        ),
    ]
